# Generated by Django 3.1.3 on 2020-12-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
